/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ControlRoomRouteImport } from './routes/control-room'
import { Route as ArticleRouteImport } from './routes/article'

const ControlRoomRoute = ControlRoomRouteImport.update({
  id: '/control-room',
  path: '/control-room',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleRoute = ArticleRouteImport.update({
  id: '/article',
  path: '/article',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/article': typeof ArticleRoute
  '/control-room': typeof ControlRoomRoute
}
export interface FileRoutesByTo {
  '/article': typeof ArticleRoute
  '/control-room': typeof ControlRoomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/article': typeof ArticleRoute
  '/control-room': typeof ControlRoomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/article' | '/control-room'
  fileRoutesByTo: FileRoutesByTo
  to: '/article' | '/control-room'
  id: '__root__' | '/article' | '/control-room'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ArticleRoute: typeof ArticleRoute
  ControlRoomRoute: typeof ControlRoomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/control-room': {
      id: '/control-room'
      path: '/control-room'
      fullPath: '/control-room'
      preLoaderRoute: typeof ControlRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article': {
      id: '/article'
      path: '/article'
      fullPath: '/article'
      preLoaderRoute: typeof ArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ArticleRoute: ArticleRoute,
  ControlRoomRoute: ControlRoomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
