/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as ControlRoomRouteImport } from './routes/control-room'
import { Route as ArticleRouteImport } from './routes/article'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as CategoryArticleSlugRouteImport } from './routes/$category.$articleSlug'
import { Route as ApiPublicSubscribeRouteImport } from './routes/api/public/subscribe'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoomRoute = ControlRoomRouteImport.update({
  id: '/control-room',
  path: '/control-room',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleRoute = ArticleRouteImport.update({
  id: '/article',
  path: '/article',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryArticleSlugRoute = CategoryArticleSlugRouteImport.update({
  id: '/$category/$articleSlug',
  path: '/$category/$articleSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSubscribeRoute = ApiPublicSubscribeRouteImport.update({
  id: '/api/public/subscribe',
  path: '/api/public/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/article': typeof ArticleRoute
  '/control-room': typeof ControlRoomRoute
  '/issues': typeof IssuesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$category/$articleSlug': typeof CategoryArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/api/public/subscribe': typeof ApiPublicSubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/article': typeof ArticleRoute
  '/control-room': typeof ControlRoomRoute
  '/issues': typeof IssuesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$category/$articleSlug': typeof CategoryArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/api/public/subscribe': typeof ApiPublicSubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/article': typeof ArticleRoute
  '/control-room': typeof ControlRoomRoute
  '/issues': typeof IssuesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$category/$articleSlug': typeof CategoryArticleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/api/public/subscribe': typeof ApiPublicSubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/article'
    | '/control-room'
    | '/issues'
    | '/sitemap.xml'
    | '/$category/$articleSlug'
    | '/category/$slug'
    | '/api/public/subscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/article'
    | '/control-room'
    | '/issues'
    | '/sitemap.xml'
    | '/$category/$articleSlug'
    | '/category/$slug'
    | '/api/public/subscribe'
  id:
    | '__root__'
    | '/'
    | '/article'
    | '/control-room'
    | '/issues'
    | '/sitemap.xml'
    | '/$category/$articleSlug'
    | '/category/$slug'
    | '/api/public/subscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticleRoute: typeof ArticleRoute
  ControlRoomRoute: typeof ControlRoomRoute
  IssuesRoute: typeof IssuesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CategoryArticleSlugRoute: typeof CategoryArticleSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ApiPublicSubscribeRoute: typeof ApiPublicSubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-room': {
      id: '/control-room'
      path: '/control-room'
      fullPath: '/control-room'
      preLoaderRoute: typeof ControlRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article': {
      id: '/article'
      path: '/article'
      fullPath: '/article'
      preLoaderRoute: typeof ArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category/$articleSlug': {
      id: '/$category/$articleSlug'
      path: '/$category/$articleSlug'
      fullPath: '/$category/$articleSlug'
      preLoaderRoute: typeof CategoryArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/subscribe': {
      id: '/api/public/subscribe'
      path: '/api/public/subscribe'
      fullPath: '/api/public/subscribe'
      preLoaderRoute: typeof ApiPublicSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticleRoute: ArticleRoute,
  ControlRoomRoute: ControlRoomRoute,
  IssuesRoute: IssuesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CategoryArticleSlugRoute: CategoryArticleSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  ApiPublicSubscribeRoute: ApiPublicSubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
